on: 
  push:
    tags:
      - "**"
      
jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Download releaseartifacts
        uses: actions/download-artifact@v2
        with:
          name: release-artifacts
          path: release
      - name: Generate checksum
        uses: jmgilman/actions-generate-checksum@v1
        with:
          patterns: |
            release/*.zip
            release/*.tar.gz
